name: Deploy Website

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:

  # ========================================
  # GitHub Pages
  # ========================================
  github-pages:
    name: Deploy to GitHub Pages

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # 1. Get code
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      # 3. Upload website
      - name: Upload website files
        uses: actions/upload-pages-artifact@v4
        with:
          path: "."

      # 4. Deploy GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


  # ========================================
  # Vercel
  # ========================================
  vercel:
    name: Deploy to Vercel

    runs-on: ubuntu-latest

    steps:

      # 1. Get code
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # 3. Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel deploy --prod --yes --token="${{ secrets.VERCEL_TOKEN }}"